services:
  main:
    build: main
    env_file:
      - .env
    ports:
      - ${TOWER_MAIN_LISTEN_PORT}:${TOWER_MAIN_LISTEN_PORT}
    secrets:
      - db-password
      - redis-password
      - auth-jwt-key
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "echo hello"

  auth:
    build: auth
    env_file:
      - .env
    ports:
      - 8000:8000
    secrets:
      - db-password
      - redis-password
      - auth-jwt-key
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    build: db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${TOWER_DB_HOST}
      POSTGRES_PORT: ${TOWER_DB_PORT}
      POSTGRES_USER: ${TOWER_DB_USER}
      POSTGRES_PASSWORD_FILE: ${TOWER_DB_PASSWORD_FILE}
      POSTGRES_DB: ${TOWER_DB_NAME}
    expose:
      - ${TOWER_DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    secrets:
      - db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 0s
      interval: 5s
      timeout: 5s 
      retries: 5
  
  redis:
    image: redis:alpine
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis-password
    expose:
      - 6379
    secrets:
      - redis-password
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
    command: sh -c "redis-server --requirepass $(cat $$REDIS_PASSWORD_FILE)"

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db-password
  redis-password:
    file: secrets/redis-password
  auth-jwt-key:
    file: secrets/auth-jwt-key