services:
  main:
    build: ./main
    env_file:
      - .env
    ports:
      - 30000:30000
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started

  auth:
    build: ./auth
    env_file:
      - .env
      - ./auth/auth.env
    ports:
      - 8000:8000
    secrets:
      - db-password
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started

  db:
    build: ./db
    environment:
      POSTGRES_HOST: ${TOWER_DB_HOST}
      POSTGRES_PORT: ${TOWER_DB_PORT}
      POSTGRES_USER: ${TOWER_DB_USER}
      POSTGRES_PASSWORD_FILE: ${TOWER_DB_PASSWORD_FILE}
      POSTGRES_DB: ${TOWER_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    secrets:
      - db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:alpine

volumes:
  db-data:

secrets:
  db-password:
    file: db/secrets/db-password