services:
  main-server:
    build: .
    ports:
      - 30000:30000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_DB: tower
      POSTGRES_USER: tower_server
      POSTGRES_PASSWORD: password
    depends_on:
      - db

  auth-server:
    build: ./auth
    working_dir: /app
    volumes:
      - ./auth/:/app
    environment:
      POSTGRES_DB: tower
      POSTGRES_USER: tower_server
      POSTGRES_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:16-alpine
#    restart: always
    volumes:
      - tower-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tower
      POSTGRES_USER: tower_server
      POSTGRES_PASSWORD: password

volumes:
  tower-db-data: {}